server:
  port: 8819

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem?serverTimezone=UTC
    username: root
    password: w2453928297
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    instance:
      instance-id: menu
      prefer-ip-address: true

info:
    app.name: menu
    company.name: com.wys
    build.artifactId: $project.artifactId$
    build.version: $project.version$